import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import myPrisma from '@/config/prisma'


export default function Home() {
  return (
    <>
      <Head>
        <title>Ideas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 style={{textAlign:"center", color:"#fee"}}>Ideas App</h1>
      </main>
    </>
  )
}

export async function getServerSideProps(){
  const tags = await myPrisma.tag.findMany()
  console.log(tags)
  return {
    props: {}
  }
}